/** 得到数据 */
export const GET_DEPARTMENT_LIST_STATISTIC = 'DEPARTMENT_LIST_STATISTIC/GET';
/** 测试 */
export const TEST_DEPARTMENT_LIST_STATISTIC = 'DEPARTMENT_LIST_STATISTIC/TEST';

/** 错误 */
export const ERROR_DEPARTMENT_LIST_STATISTIC = 'DEPARTMENT_LIST_STATISTIC/ERROR';

